[package]
name = "anansi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "lib/base" }
log = "0.4.17"
parking_lot = "0.12.1"
serde = "1.0.152"

[workspace]
members = ["lib/*"]


