[build]
rustflags = ["-C", "target-cpu=native"]
target = "aarch64-apple-darwin"

[test]
rustflags = ["-C", "target-cpu=native"]
target = "aarch64-apple-darwin"

[target]
default = "aarch64-apple-darwin"