models:
  - name: INSTRUCTOR_LARGE
    class: ModelClass_INSTRUCTOR
    num_threads: 4
    parallel_execution: true
  # this is the default OPENAI CLIP model that is used by JinaAi
  # including it makes it easy to compare this embedding service.
  # - name: VIT_L_14_336_OPENAI
  #   class: ModelClass_CLIP
  #   num_threads: 4
